name: "1 - [FEAT] Build & PR"

on:
  push:
    branches:
      - 'feature**'
      - 'fix**'
      -
  workflow_call:
    inputs:
      application-publish:
        required: false
        type: boolean
        default: false
      deploy-dev-account:
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Building the app
      



    